---
- hosts: donald
  become: true
  remote_user: "{{ master.root_user }}"
  vars_files:
    - ../vars/donald.yml

  tasks:
    - name: change hostname
      hostname:
        name: "{{ master.hostname }}"
