---
- hosts: joshua

  # become_user: "{{ user }}"
  become: true
  vars_files:
    - ../host_vars/joshua.yml

  # vars:
  # user_dir: "{{ansible_env.HOME}}"

  roles:
    - "../roles/i3-wm"
    - "../roles/snapd"
    - "../roles/lxd"

  tasks:
    - name: change hostname
      hostname:
        name: "{{ hostname }}"

    - name: create dir for all the configs
      file:
        path: "{{ ansible_files_dir }}"
        state: directory

    # - name: move cron script to our dir
    #   ansible.builtin.template:
    #     mode: 770
    #     src: ../files/run_cron.sh.j2
    #     dest: "{{ ansible_files_dir }}/run_cron.sh"

    # - name: setup a cron job that runs ansible
    #   ansible.builtin.cron:
    #     name: "check dirs"
    #     minute: "0"
    #     hour: "12,14,20,22"
    #     job: "./{{ ansible_files_dir }}/run_cron.sh"

    - name: install apt packages
      ansible.builtin.apt:
        name:
          - neovim
